package:
  name: ros-noetic-moveit-ros-perception
  version: 1.1.11
source:
  git_url: https://github.com/ros-gbp/moveit-release.git
  git_rev: release/noetic/moveit_ros_perception/1.1.11-1
  folder: ros-noetic-moveit-ros-perception/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - eigen
    - freeglut
    - glew
    - libgomp
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
    - ros-noetic-image-transport
    - ros-noetic-message-filters
    - ros-noetic-moveit-core
    - ros-noetic-moveit-msgs
    - ros-noetic-moveit-ros-occupancy-map-monitor
    - ros-noetic-moveit-ros-planning
    - ros-noetic-nodelet
    - ros-noetic-object-recognition-msgs
    - ros-noetic-pluginlib
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-rosunit
    - ros-noetic-sensor-msgs
    - ros-noetic-tf2
    - ros-noetic-tf2-eigen
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-ros
    - ros-noetic-urdf
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - freeglut
    - glew
    - libgomp
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-cv-bridge
    - ros-noetic-image-transport
    - ros-noetic-message-filters
    - ros-noetic-moveit-core
    - ros-noetic-moveit-msgs
    - ros-noetic-moveit-ros-occupancy-map-monitor
    - ros-noetic-moveit-ros-planning
    - ros-noetic-nodelet
    - ros-noetic-object-recognition-msgs
    - ros-noetic-pluginlib
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-tf2
    - ros-noetic-tf2-eigen
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-ros
    - ros-noetic-urdf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
