package:
  name: ros-noetic-ros-ign-image
  version: 0.111.2
source:
  git_url: https://github.com/ros-gbp/ros_ign-release.git
  git_rev: release/noetic/ros_ign_image/0.111.2-1
  folder: ros-noetic-ros-ign-image/src/work
  patches:
    - patch/ros-noetic-ros-ign-image.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 17
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - libignition-msgs8
    - libignition-transport11
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.5 noetic
    - ros-noetic-catkin
    - ros-noetic-image-transport
    - ros-noetic-ros-ign-bridge
    - ros-noetic-roscpp
    - ros-noetic-rostest
    - ros-noetic-sensor-msgs
  run:
    - libignition-msgs8
    - libignition-transport11
    - python
    - ros-distro-mutex 0.5 noetic
    - ros-noetic-image-transport
    - ros-noetic-ros-ign-bridge
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
