runners:
  - name: aws-cpu-arm-runner
    cloud: aws
    instance_type: a1.4xlarge
    # AMI for ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server + docker
    machine_image: ami-00dace5a405a9887e
    preemptible: false
    labels:
       - cirun-linux-aarch64
