runners:
  - name: aws-cpu-arm-runner
    cloud: aws
    instance_type: a1.xlarge
    # AMI for ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server
    machine_image: ami-00dace5a405a9887e
    #machine_image: ami-0229f8cfc24033d05
    preemptible: false
    labels:
      - cirun-linux-aarch64
