# Generated by vinca http://github.com/RoboStack/vinca.
# DO NOT EDIT!
if ($null -eq ${env:CONDA_PREFIX}) { Exit }

# Don't do anything when we are in conda build.
if ($null -ne ${env:SYS_PREFIX}) { Exit 0 }

$Env:QT_PLUGIN_PATH="${env:CONDA_PREFIX}\Library\plugins"

& "${env:CONDA_PREFIX}\Library\local_setup.ps1"

$Env:PYTHONHOME=''
$Env:ROS_OS_OVERRIDE='conda:win64'
$Env:ROS_ETC_DIR="${env:CONDA_PREFIX}\Library\etc\ros"
$Env:AMENT_PREFIX_PATH="${env:CONDA_PREFIX}\Library"
$Env:AMENT_PYTHON_EXECUTABLE="${env:CONDA_PREFIX}\python.exe"
