:: Generated by vinca http://github.com/RoboStack/vinca.
:: DO NOT EDIT!
setlocal

set "PYTHONPATH=%LIBRARY_PREFIX%\lib\site-packages;%SP_DIR%"

pushd %SRC_DIR%\%PKG_NAME%\src\work

:: If there is a setup.cfg that contains install-scripts then we should not
:: set it here
set "INSTALL_SCRIPTS_ARG=--install-scripts=%LIBRARY_PREFIX%\bin"
findstr install[-_]scripts setup.cfg
if "%errorlevel%" == "0" (
  set INSTALL_SCRIPTS_ARG=
)

%PYTHON% setup.py install ^
    --prefix=%LIBRARY_PREFIX% ^
    --install-lib=%SP_DIR% ^
    %INSTALL_SCRIPTS_ARG%

if errorlevel 1 exit 1
