:: Generated by vinca http://github.com/RoboStack/vinca.
:: DO NOT EDIT!
setlocal

set "PYTHONPATH=%LIBRARY_PREFIX%\lib\site-packages;%SP_DIR%"

pushd %SRC_DIR%\%PKG_NAME%\src\work

:: If there is a setup.cfg that contains install-scripts then use pip to install
findstr install[-_]scripts setup.cfg
if "%errorlevel%" == "0" (
    %PYTHON% -m pip install . --no-deps -vvv
) else (
    set "INSTALL_SCRIPTS_ARG=--install-scripts=%LIBRARY_PREFIX%\bin"
    %PYTHON% setup.py install --single-version-externally-managed --record=files.txt ^
        --prefix=%LIBRARY_PREFIX% ^
        --install-lib=%SP_DIR% ^
        %INSTALL_SCRIPTS_ARG%
)

if errorlevel 1 exit 1
