# Generated by vinca http://github.com/RoboStack/vinca.
# DO NOT EDIT!

pushd $SRC_DIR/$PKG_NAME/src/work

# If there is a setup.cfg that contains install-scripts then we should not set it here
result=$?
grep -q "install[-_]scripts" setup.cfg || true
if [ $result -eq 0 ]; then
  $PYTHON -m pip install . --no-deps -vvv
else
  # Remove e.g. ros-humble- from PKG_NAME
  PKG_NAME_SHORT=${PKG_NAME#*ros-noetic-}
  # Substitute "-" with "_"
  PKG_NAME_SHORT=${PKG_NAME_SHORT//-/_}
  INSTALL_SCRIPTS_ARG="--install-scripts=$PREFIX/lib/$PKG_NAME_SHORT"
  echo "WARNING: setup.cfg not set, will set INSTALL_SCRIPTS_ARG to: $INSTALL_SCRIPTS_ARG"
  $PYTHON setup.py install --prefix="$PREFIX" --install-lib="$SP_DIR" $INSTALL_SCRIPTS_ARG
fi
