# Project overrides
macos_min_version:             # [osx and x86_64]
  - 10.9                       # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - 10.9                       # [osx and x86_64]
