pkg-config:
  conda-forge: [pkg-config]
python-rospkg:
  conda-forge: [rospkg]
python3-rospkg:
  conda-forge: [rospkg]
python-rospkg-modules:
  conda-forge: [rospkg]
python3-rospkg-modules:
  conda-forge: [rospkg]
boost:
  conda-forge: [boost]
libboost-python-dev:
  conda-forge: [boost]
python-argparse:
  conda-forge: []
python-catkin-pkg:
  conda-forge: [catkin_pkg]
python3-catkin-pkg:
  conda-forge: [catkin_pkg]
python:
  conda-forge: [python]
python-dev:
  conda-forge: [python]
python3:
  conda-forge: [python]
python3-dev:
  conda-forge: [python]
python-rosdep:
  conda-forge: [rosdep]
python3-rosdep:
  conda-forge: [rosdep]
python-empy:
  conda-forge: [empy]
python3-empy:
  conda-forge: [empy]
tinyxml:
  conda-forge: [tinyxml]
tinyxml2:
  conda-forge: [tinyxml2]
gtest:
  conda-forge: [gtest]
cmake:
  conda-forge: [cmake]
google-mock:
  conda-forge: [gmock]
python-mock:
  conda-forge: [mock]
python3-mock:
  conda-forge: [mock]
python-nose:
  conda-forge: [nose]
python3-nose:
  conda-forge: [nose]
python-coverage:
  conda-forge: [coverage]
python3-coverage:
  conda-forge: [coverage]
libconsole-bridge-dev:
  conda-forge: [console_bridge]
python-yaml:
  conda-forge: [pyyaml]
python3-yaml:
  conda-forge: [pyyaml]
python-setuptools:
  conda-forge: [setuptools]
python3-setuptools:
  conda-forge: [setuptools]
python-catkin-pkg-modules:
  conda-forge: [catkin_pkg]
python3-catkin-pkg-modules:
  conda-forge: [catkin_pkg]
python-rosdep-modules:
  conda-forge: [rosdep]
python3-rosdep-modules:
  conda-forge: [rosdep]
libboost-system-dev:
  conda-forge: [boost-cpp]
libboost-date-time-dev:
  conda-forge: [boost-cpp]
libboost-thread-dev:
  conda-forge: [boost-cpp]
libpoco-dev:
  conda-forge: [poco]
python-gnupg:
  conda-forge: [python-gnupg]
python3-gnupg:
  conda-forge: [python-gnupg]
python-imaging:
  conda-forge: [pillow]
python3-pil:
  conda-forge: [pillow]
python-crypto:
  conda-forge: [pycrypto]
bzip2:
  conda-forge: [bzip2]
libssl-dev:
  conda-forge: [openssl]
libgpgme-dev:
  conda-forge:
    win64: []
    unix: [gpgme]
log4cxx:
  conda-forge: [log4cxx]
apr:
  conda-forge: [apr]
python-netifaces:
  conda-forge: [netifaces]
python3-netifaces:
  conda-forge: [netifaces]
python-paramiko:
  conda-forge: [paramiko]
python3-paramiko:
  conda-forge: [paramiko]
sbcl:
  conda-forge:
    win64: []
    unix: [sbcl]
lz4:
  conda-forge: [lz4]
python-defusedxml:
  conda-forge: [defusedxml]
python3-defusedxml:
  conda-forge: [defusedxml]
python-numpy:
  conda-forge: [numpy]
python3-numpy:
  conda-forge: [numpy]
python3-pytest:
  conda-forge: [pytest]
python3-rosdistro-modules:
  conda-forge: [rosdistro]
python3-lark-parser:
  conda-forge: [lark-parser]
cppcheck:
  conda-forge: [cppcheck]
python3-mypy:
  conda-forge: [mypy]
zlib:
  conda-forge: [zlib]
python3-pkg-resources:
  conda-forge: []
python3-cryptography:
  conda-forge: [cryptography]
python3-ifcfg:
  conda-forge: [ifcfg]
python3-flake8:
  conda-forge: [flake8]
python3-pytest-mock:
  conda-forge: [pytest-mock]
yaml:
  conda-forge: [yaml]
asio:
  conda-forge: [asio]
git:
  conda-forge: [git]
spdlog:
  conda-forge: [spdlog]
pcre:
  conda-forge: [pcre]
pydocstyle:
  conda-forge: [pydocstyle]
libxml2-utils:
  conda-forge: [libxml2]
libcunit-dev:
  conda-forge: []
uncrustify:
  conda-forge: [uncrustify]
python-lxml:
  conda-forge: [lxml]
python3-lxml:
  conda-forge: [lxml]
openssl:
  conda-forge: [openssl]
eigen:
  conda-forge: [eigen]
assimp:
  conda-forge: [assimp]
assimp-dev:
  conda-forge: [assimp]
libqt5-opengl:
  conda-forge:
    win64: [qt 5.12.6]
    linux: [qt 5.12, REQUIRE_OPENGL]
    osx: [qt 5.12, REQUIRE_OPENGL]
libqt5-opengl-dev:
  conda-forge:
    win64: [qt 5.12.6]
    linux: [qt 5.12, REQUIRE_OPENGL]
    osx: [qt 5.12, REQUIRE_OPENGL]
libqt5-widgets:
  conda-forge:
    win64: [qt 5.12.6]
    linux: [qt 5.12, REQUIRE_OPENGL]
    osx: [qt 5.12, REQUIRE_OPENGL]
curl:
  conda-forge: [libcurl]
qtbase5-dev:
  conda-forge:
    win64: [qt 5.12.6]
    linux: [qt 5.12, REQUIRE_OPENGL]
    osx: [qt 5.12, REQUIRE_OPENGL]
libqt5-gui:
  conda-forge:
    win64: [qt 5.12.6]
    linux: [qt 5.12, REQUIRE_OPENGL]
    osx: [qt 5.12, REQUIRE_OPENGL]
libqt5x11extras5-dev:
  conda-forge:
    win64: [qt 5.12.6]
    linux: [qt 5.12, REQUIRE_OPENGL]
    osx: [qt 5.12, REQUIRE_OPENGL]
libqt5-core:
  conda-forge:
    win64: [qt 5.12.6]
    linux: [qt 5.12]
    osx: [qt 5.12]
qt5-qmake:
  conda-forge:
    win64: [qt 5.12.6]
    linux: [qt 5.12]
    osx: [qt 5.12]
qt5-image-formats-plugins:
  conda-forge:
    win64: [qt 5.12.6]
    linux: [qt 5.12]
    osx: [qt 5.12]
python-qt5-bindings:
  conda-forge:
    win64: [pyqt]
    osx: [pyqt 5.12]
    linux: [pyqt 5.12]
python3-qt5-bindings:
  conda-forge:
    win64: [pyqt]
    osx: [pyqt 5.12]
    linux: [pyqt 5.12]
python3-qt5-bindings-webkit:
  conda-forge:
    win64: [pyqt]
    osx: [pyqt 5.12]
    linux: [pyqt 5.12]
python3-qt5-bindings-gl:
  conda-forge:
    win64: [pyqt]
    osx: [pyqt 5.12]
    linux: [pyqt 5.12]
libfreetype6-dev:
  conda-forge: [freetype]
libfreetype6:
  conda-forge: [freetype]
opengl:
  conda-forge:
    win64: []
    unix: [REQUIRE_OPENGL]
libxaw:
  conda-forge:
    win64: []
    unix: [xorg-libxaw]
libxrandr:
  conda-forge:
    win64: []
    unix: [xorg-libxrandr]
libopencv-dev:  # opencv needs to be pinned, otherwise different packages might pull in different versions
  conda-forge: [py-opencv 4.5, libopencv 4.5]
python-opencv:
  conda-forge: [py-opencv 4.5, libopencv 4.5]
python3-opencv:
  conda-forge: [py-opencv 4.5, libopencv 4.5]
python-pydot:
  conda-forge: [pydot]
python3-pydot:
  conda-forge: [pydot]
python-matplotlib:
  conda-forge: [matplotlib-base]
python3-matplotlib:
  conda-forge: [matplotlib-base]
python-psutil:
  conda-forge: [psutil]
python3-psutil:
  conda-forge: [psutil]
sdl-image:
  conda-forge: [sdl_image]
graphicsmagick:
  conda-forge: [graphicsmagick]
libboost-program-options:
  conda-forge: [boost-cpp]
sdl:
  conda-forge: [sdl]
libzmq3-dev:
  conda-forge: [zeromq]
libboost-program-options-dev:
  conda-forge:
    win64: [boost]
    unix: [boost-cpp]
libboost-filesystem-dev:
  conda-forge: [boost-cpp]
libboost-regex-dev:
  conda-forge: [boost-cpp]
libboost-chrono-dev:
  conda-forge: [boost-cpp]
libboost-dev:
  conda-forge: [boost-cpp]
python-cairo:
  conda-forge: [pycairo]
python3-cairo:
  conda-forge: [pycairo]
graphviz:
  conda-forge:
    win64: []  # see https://github.com/conda-forge/graphviz-feedstock/issues/47
    unix: [graphviz]
python-pygraphviz:
  conda-forge:
    win64: []
    unix: [pygraphviz]
python3-pygraphviz:
  conda-forge:
    win64: []
    unix: [pygraphviz]
python-opengl:
  conda-forge: [pyopengl, REQUIRE_OPENGL]
python3-opengl:
  conda-forge: [pyopengl, REQUIRE_OPENGL]
libogre-dev:
  conda-forge: [ogre 1.10]
libogre:
  conda-forge: [ogre 1.10]
liburdfdom-dev:
  conda-forge: [urdfdom 1.0]
liburdfdom-tools:
  conda-forge: [urdfdom 1.0]
liburdfdom-headers-dev:
  conda-forge: [urdfdom_headers 1.0]
yaml-cpp:
  conda-forge: [yaml-cpp]
python-wxtools:
  conda-forge: [wxpython]
wxpython:
  conda-forge: [wxpython]
wx-common:
  conda-forge: [wxpython]
python-pycryptodome:
  conda-forge: [pycryptodome, pycryptodomex]
python3-pycryptodome:
  conda-forge: [pycryptodome, pycryptodomex]
uuid:
  conda-forge:
    win64: []
    linux: [libuuid]
    osx: []  # see https://github.com/regro/cf-scripts/issues/417
python-sip:
  conda-forge: [sip]
cppunit:
  conda-forge:
    win64: []
    unix: [cppunit]
libfcl-dev:
  conda-forge: [fcl]
libqhull:
  conda-forge: [qhull]
lcov:
  conda-forge: [lcov]
glut:
  conda-forge:
    win64: [freeglut 3.0.0]  # see https://github.com/conda-forge/freeglut-feedstock/issues/26
    linux: [freeglut]
    osx: []  # see https://github.com/conda-forge/freeglut-feedstock/issues/23
doxygen:
  conda-forge: [doxygen]
libglew-dev:
  conda-forge: [glew]
python-pyassimp:
  conda-forge: [assimp]
python3-pyassimp:
  conda-forge: [assimp]
libpcl-all-dev:
  conda-forge: [pcl 1.11]
libpcl-all:
  conda-forge: [pcl 1.11]
libogg:
  conda-forge: [libogg]
gtk3:
  conda-forge: [libglib, glib, gtk3, harfbuzz, libxcb, pthread-stubs, xorg-libxau, xorg-libxi, xorg-libxrandr, xorg-libxcursor, xorg-libxtst, xorg-libxcomposite, xorg-libxdamage, xorg-libxinerama, xorg-xineramaproto, epoxy, REQUIRE_GL]
libtheora:
  conda-forge: [libtheora]
liborocos-kdl:
  conda-forge: [orocos-kdl]
liborocos-kdl-dev:
  conda-forge: [orocos-kdl]
python3-pykdl:
  conda-forge: [python-orocos-kdl]
gtk2:
  conda-forge: [gtk2]
gazebo11:
  conda-forge:
    - "gazebo 11.*"
libgazebo11-dev:
  conda-forge:
    - "gazebo 11.*"
gazebo9:
  conda-forge:
    - "gazebo 9.*"
libgazebo9-dev:
  conda-forge:
    - "gazebo 9.*"
gazebo:
  conda-forge:
    - gazebo
libfltk-dev:
  conda-forge: [fltk]
libjpeg:
  conda-forge: [libjpeg-turbo]
libtool:
  conda-forge: [libtool]
python-autobahn:
  conda-forge: [autobahn]
python-tornado:
  conda-forge: [tornado]
python-bson:
  conda-forge: [pymongo]
python-twisted-core:
  conda-forge: [twisted]
bullet:
  conda-forge:
    win64: [bullet 2.88]
    unix: [bullet]
suitesparse:
  conda-forge: [suitesparse]
libpcap:
  conda-forge: [libpcap]
libblas-dev:
  conda-forge: [libblas]
libopenblas-dev:
  conda-forge: [libblas]
liblapack-dev:
  conda-forge: [liblapack]
libceres-dev:
  conda-forge: [ceres-solver]
tbb:
  conda-forge: [tbb, tbb-devel]
libsqlite3-dev:
  conda-forge: ["sqlite 3.*"]
proj:
  conda-forge: [proj]
libvtk-qt:
  conda-forge: [vtk]
libfreenect-dev:
  conda-forge: []
libopenni-dev:
  conda-forge: []
tango-icon-theme:
  conda-forge: []
ffmpeg:
  conda-forge: [ffmpeg]
python3-bson:
  # not sure about this one actually...; could also be https://github.com/conda-forge/pymongo-feedstock
  conda-forge: [mongodb]
python3-tornado:
  conda-forge: [tornado]
python3-autobahn:
  conda-forge: [autobahn]
python3-twisted:
  conda-forge: [twisted]
geographiclib:
  conda-forge: [geographiclib-cpp]
geographiclib-tools:
  conda-forge: [geographiclib-cpp]
python3-future:
  conda-forge: [future]
libccd-dev:
  conda-forge: [libccd]
libgsl:
  conda-forge: [gsl]
virtualenv:
  conda-forge: [virtualenv]
libturbojpeg:
  conda-forge: [libjpeg-turbo]
python3-requests-oauthlib:
  conda-forge: [requests-oauthlib]
python3-sklearn:
  conda-forge: [scikit-learn]
libreadline-dev:
  conda-forge: [readline]
libreadline:
  conda-forge: [readline]
python3-pip:
  conda-forge: [pip]
cython:
  conda-forge: [cython]
libusb-1.0:
  conda-forge: [libusb]
libusb-dev:
  conda-forge: [libusb]
libusb-1.0-dev:
  conda-forge: [libusb]
python-dlib:
  conda-forge: [dlib]
libxi-dev:
  conda-forge: [xorg-libxi]
subversion:
  conda-forge: [subversion]
protobuf:
  conda-forge: [libprotobuf, protobuf]
protobuf-dev:
  conda-forge: [libprotobuf, protobuf]
gstreamer1.0:
  conda-forge: [gstreamer]
libgstreamer1.0-dev:
  conda-forge: [gstreamer]
gstreamer1.0-plugins-base:
  conda-forge: [gst-plugins-base]
libgstreamer-plugins-base1.0-dev:
  conda-forge: [gst-plugins-base]
gstreamer1.0-plugins-good:
  conda-forge: [gst-plugins-good]
muparser:
  conda-forge: [muparser]
python3-texttable:
  conda-forge: [texttable]
python3-h5py:
  conda-forge: [h5py]
python3-colorama:
  conda-forge: [colorama]
libjsoncpp:
  conda-forge: [jsoncpp]
libjsoncpp-dev:
  conda-forge: [jsoncpp]
collada-dom:
  conda-forge: [collada-dom]
libnlopt-dev:
  conda-forge: [nlopt]
libnlopt-cxx-dev:
  conda-forge: [nlopt]
python3-requests:
  conda-forge: [requests]
libhdf5-dev:
  conda-forge: [hdf5]
wget:
  conda-forge: [wget]
mongodb:
  conda-forge: [mongodb]
libqwt-qt5-dev:
  conda-forge: [qwt]
g++-static:
  conda-forge: [cxx-compiler]
python3-pep8:
  conda-forge: [pep8]
python3-sphinx:
  conda-forge: [sphinx]
zbar:
  conda-forge: [zbar]
wxwidgets:
  conda-forge: [wxwidgets]
libglfw3-dev:
  conda-forge: [glfw 3.*]
libspnav-dev:
  conda-forge: [libspnav]
pydrive-pip:
  conda-forge: [pydrive]
time:
  conda-forge: [time]
python-tabulate-pip:
  conda-forge: [tabulate]
pugixml-dev:
  conda-forge: [pugixml]
kitchen:
  conda-forge: [kitchen]
swig:
  conda-forge: [swig]
python3-catkin-tools:
  conda-forge: [catkin_tools]
python-six:
  conda-forge: [six]
python3-six:
  conda-forge: [six]
libdc1394-dev:
  conda-forge: [libdc1394]
python-chainer-pip:
  conda-forge: [chainer]
python3-cherrypy3:
  conda-forge: [cherrypy]
libnl-3:
  conda-forge: [libnl 3.*]
libnl-3-dev:
  conda-forge: [libnl 3.*]
ca-certificates:
  conda-forge: [ca-certificates]
coinor-libipopt-dev:
  conda-forge: [ipopt]
alsa-oss:
  conda-forge: [alsa-lib]
armadillo:
  conda-forge: [armadillo]
nlopt:
  conda-forge: [nlopt]
libnlopt0:
  conda-forge: [nlopt]
ipython3:
  conda-forge: [ipython]
fmt:
  conda-forge: [fmt]
libncurses-dev:
  conda-forge: [ncurses]
emacs:
  conda-forge: [emacs]
libvtk:
  conda-forge: [vtk]
python-speechrecognition-pip:
  conda-forge: [speechrecognition]
ocl-icd-opencl-dev:
  conda-forge: [ocl-icd]
python3-pymongo:
  conda-forge: [pymongo]
flac:
  conda-forge: [libflac]
libflann-dev:
  conda-forge: [flann]
python-slacker-cli:
  conda-forge: [slacker]
libclang-dev:
  conda-forge: [libclang]
libmicrohttpd:
  conda-forge: [libmicrohttpd]
python-tk:
  conda-forge: [tk]
python3-tk:
  conda-forge: [tk]
libx11-dev:
  conda-forge: [xorg-libx11]
python3-click:
  conda-forge: [click]
libgflags-dev:
  conda-forge: [gflags]
python3-docutils:
  conda-forge: [docutils]
linux-kernel-headers:
  conda-forge: []
python3-imageio:
  conda-forge: [imageio]
libgoogle-glog-dev:
  conda-forge: [glog]
postgresql:
  conda-forge: [postgresql]
leveldb:
  conda-forge: [leveldb]
libgts:
  conda-forge: [gts]
python3-termcolor:
  conda-forge: [termcolor]
python3-simplejson:
  conda-forge: [simplejson]
python3-pandas:
  conda-forge: [pandas]
python3-scipy:
  conda-forge: [scipy]
libffi-dev:
  conda-forge: [libffi]
ignition-msgs5:
  conda-forge: [libignition-msgs5]
screen:
  conda-forge: [screen]
python-pyusb-pip:
  conda-forge: [pyusb]
libxml2:
  conda-forge: [libxml2]
python3-github:
  conda-forge: [pygithub]
python3-github3:
  conda-forge: [pygithub]
avahi-daemon:
  conda-forge: [python-avahi]
msgpack:
  conda-forge: [msgpack-python]
python3-msgpack:
  conda-forge: [msgpack-python]
libgeos++-dev:
  conda-forge: [geos]
python3-argcomplete:
  conda-forge: [argcomplete]
libcap-dev:
  conda-forge: [libcap]
python3-grpcio:
  conda-forge: [grpcio]
python3-pyproj:
  conda-forge: [pyproj]
rsync:
  conda-forge: [rsync]
ignition-transport8:
  conda-forge: [libignition-transport8]
python3-skimage:
  conda-forge: [scikit-image]
libpng-dev:
  conda-forge: [libpng]
unzip:
  conda-forge: [unzip]
python-gdown-pip:
  conda-forge: [gdown]
python-freezegun-pip:
  conda-forge: [freezegun]
libxmu-dev:
  conda-forge: [xorg-libxmu]
python3-ruamel.yaml:
  conda-forge: [ruamel.yaml]
bison:
  conda-forge: [bison]
gawk:
  conda-forge: [gawk]
sshpass:
  conda-forge: [sshpass]
flex:
  conda-forge: [flex]
ignition-gazebo3:
  conda-forge: [libignition-gazebo4]
