# Generated by vinca http://github.com/RoboStack/vinca.
# DO NOT EDIT!
if ($null -eq ${env:CONDA_PREFIX}) { Exit }

$Env:ROS_OS_OVERRIDE=''
$Env:ROS_DISTRO=''
$Env:ROS_ETC_DIR=''
$Env:ROS_PACKAGE_PATH=''
$Env:ROS_PYTHON_VERSION=''
$Env:ROS_VERSION=''
$Env:PYTHONHOME=''
$Env:PYTHONPATH=''
$Env:CMAKE_PREFIX_PATH=''
$Env:AMENT_PREFIX_PATH=''
$Env:COLCON_PREFIX_PATH=''
$Env:QT_PLUGIN_PATH=''
$Env:ROS_LOCALHOST_ONLY=''
$Env:ament_python_executable=''
