[workspace]
name = "ros-noetic"
description = "RoboStack repo to package ros-noetic packages as conda packages"
authors = ["Tobias Fischer <tobias.fischer@qut.edu.au>", "Wolf Vollprecht <w.vollprecht@gmail.com>", "Silvio Traversaro <silvio@traversaro.it>"]
channels = ["https://repo.prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "linux-aarch64", "win-64"]

[system-requirements]
# 2.17 is the glibc version used in centos 7
libc = { family="glibc", version="2.17" }

[dependencies]
python = ">=3.11.0,<3.12"
rattler-build = ">=0.44.0"
anaconda-client = ">=1.13.0"
cmake = "<4.0"

[target.win-64.dependencies]
# git is required by rattler-build
git = "*"

[pypi-dependencies]
# This is tipically the latest commit on main branch
vinca = { git = "https://github.com/RoboStack/vinca.git", rev = "8e6ae7e6baf1b9e3f968b465447b78a18c984ca4" }
# Uncomment this line to work with a local vinca for faster iteration, but remember to comment it back
# (and regenerate the pixi.lock) once you push the modified commit to the repo
#vinca = { path = "../vinca", editable = true }

[tasks]
remove-recipes = { cmd = "rm -rf recipes_only_patch; rm -rf recipes; mkdir recipes" }
generate-recipes = { cmd = "vinca -m", depends-on = ["remove-recipes"] }
generate-gha-workflows = { cmd = "vinca-gha --trigger-branch dummy_build_branch_as_it_is_unused -d ./recipes", depends-on = ["generate-recipes"] }
check-patches = { cmd = "python check_patches_clean_apply.py", depends-on = ["generate-recipes"] }
build = { cmd = "rattler-build build --recipe-dir ./recipes -m ./conda_build_config.yaml -c robostack-staging -c https://repo.prefix.dev/conda-forge --skip-existing", depends-on = ["generate-recipes"] }
build_one_package = { cmd = "cp ./patch/$PACKAGE.*patch ./recipes/$PACKAGE/patch/; rattler-build build --recipe ./recipes/$PACKAGE/recipe.yaml -m ./conda_build_config.yaml -c robostack-staging -c https://repo.prefix.dev/conda-forge", env = { PACKAGE = "ros-noetic-ros-workspace" } }
create_snapshot = { cmd = "vinca-snapshot -d noetic -o rosdistro_snapshot.yaml" }
# upload = "anaconda -t $ANACONDA_API_TOKEN upload"
upload = "rattler-build upload anaconda -o robostack-staging -a $ANACONDA_API_TOKEN"
