[project]
name = "ros-noetic"
# Just a convention, this is the same as the mutex package
version = "0.6.0"
description = "RoboStack repo to package ros-noetic packages as conda packages"
authors = ["Tobias Fischer <tobias.fischer@qut.edu.au>", "Wolf Vollprecht <w.vollprecht@gmail.com>", "Silvio Traversaro <silvio@traversaro.it>"]
channels = ["https://repo.prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "linux-aarch64", "win-64"]

[system-requirements]
# 2.17 is the glibc version used in centos 7
libc = { family="glibc", version="2.17" }

[tasks]
upload = "anaconda -t $ANACONDA_API_TOKEN upload"

[dependencies]
python = ">=3.11.0,<3.12"
rattler-build = ">=0.33"
anaconda-client = ">=1.12"

[target.win-64.dependencies]
# patch is required by rattler-build
m2-patch = "*"
# git is required by rattler-build
git = "*"

[feature.beta.pypi-dependencies]
# This is tipically the latest commit on rattler-build-humble branch
vinca = { git ="https://github.com/RoboStack/vinca.git", rev = "45af742aa5fa5119b884f4bb5845084e70206091" }
# Uncomment this line to work with a local vinca for faster iteration, but remember to comment it back
# (and regenerate the pixi.lock) once you push the modified commit to the repo
#vinca = { path = "../vinca", editable = true }

[feature.beta.tasks]
generate-recipes = { cmd = "vinca -m", depends_on = ["rename-file"] }
remove-file = { cmd = "rm vinca.yaml; rm -rf recipes" }
copy_additional_recipes = { cmd = "sh -c 'find additional_recipes/* -maxdepth 0 -type d -exec ln -s ../{} recipes/ \\;'" }
build = { cmd = "rattler-build build --recipe-dir ./recipes -m ./conda_build_config.yaml --skip-existing", depends_on = ["generate-recipes", "copy_additional_recipes"] }
build_one_package = { cmd = "cp ./patch/$PACKAGE.*patch ./recipes/$PACKAGE/patch/; rattler-build build --recipe ./recipes/$PACKAGE/recipe.yaml -m ./conda_build_config.yaml", env = { PACKAGE = "ros-noetic-ros-base" } }

[environments]
beta = ["beta"]

[target.linux-64.tasks]
rename-file = { cmd = "ln -s vinca_linux_64.yaml vinca.yaml", depends_on = ["remove-file"] }

[target.osx-64.tasks]
rename-file = { cmd = "ln -s vinca_osx.yaml vinca.yaml", depends_on = ["remove-file"] }

[target.osx-arm64.tasks]
rename-file = { cmd = "ln -s vinca_osx_arm64.yaml vinca.yaml", depends_on = ["remove-file"] }

[target.linux-aarch64.tasks]
rename-file = { cmd = "ln -s vinca_linux_aarch64.yaml vinca.yaml", depends_on = ["remove-file"] }

[target.win-64.tasks]
# Workaround for https://github.com/prefix-dev/rattler-build/issues/1295,
# remove once a new version of rattler-build is released and replace it with a constraint on rattler-build version
install-working-rattler-build = { cmd = "curl -L -o $CONDA_PREFIX/rattler-build.exe https://github.com/traversaro/rattler-build-1295-mre/releases/download/fixed-rattler-build/rattler-build.exe" }
rename-file = { cmd = "cp vinca_win.yaml vinca.yaml", depends_on = ["remove-file", "install-working-rattler-build"] }
