package:
  name: ros-noetic-hpp-fcl
  version: "3.0.0"

build:
  number: 21

requirements:
  run:
    - hpp-fcl ==3.0.0

about:
  homepage: https://github.com/conda-forge/hpp-fcl-feedstock
  license: BSD-3-Clause
  summary: |
    An extension of the Flexible Collision Library
extra:
  recipe-maintainers:
    - ros-forge
