package:
  name: ros-noetic-eigenpy
  version: "3.1.0"

build:
  number: 21

requirements:
  run:
    - eigenpy 3.1.0


about:
  home: https://github.com/conda-forge/eigenpy-feedstock
  license: BSD-2-Clause
  summary: |
    Bindings between Numpy and Eigen using Boost.Python
extra:
  recipe-maintainers:
    - ros-forge
