package:
  name: ros-noetic-eigenpy
  version: "3.10.1"

build:
  number: 0

requirements:
  run:
    - eigenpy ==3.10.1

about:
  homepage: https://github.com/conda-forge/eigenpy-feedstock
  license: BSD-3-Clause
  summary: |
    Bindings between Numpy and Eigen using Boost.Python
extra:
  recipe-maintainers:
    - ros-forge
