package:
  name: ros-noetic-eigenpy
  # We use 3.10.0 as 3.10.1 is not compatible with numpy 1.26
  # Once we bump the numpy version, we can update this back to 3.10.1
  version: "3.10.0"

build:
  number: 22

requirements:
  run:
    - eigenpy ==3.10.0

about:
  homepage: https://github.com/conda-forge/eigenpy-feedstock
  license: BSD-3-Clause
  summary: |
    Bindings between Numpy and Eigen using Boost.Python
extra:
  recipe-maintainers:
    - ros-forge
