package:
  name: ros-noetic-jackal-navigation
  version: 0.8.5
about:
  home: http://wiki.ros.org/jackal_navigation
  license:
    - BSD
  summary: Launch files and code for autonomous navigation of the Jackal
  maintainers:
    - Mike Purvis (mpurvis@clearpathrobotics.com)
extra:
  recipe-maintainers:
    - robostack
build:
  number: 3
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh


source:
  git_url: https://github.com/clearpath-gbp/jackal-release.git
  git_rev: release/noetic/jackal_navigation/0.8.5-1
  folder: ros-noetic-jackal-navigation/src/work
requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-roslaunch
    - ros-noetic-amcl
    - ros-noetic-gmapping
    - ros-noetic-map-server
    - ros-noetic-move-base
    - ros-noetic-urdf
    - ros-noetic-xacro
  run:
    - python
    - ros-noetic-amcl
    - ros-noetic-gmapping
    - ros-noetic-map-server
    - ros-noetic-move-base
    - ros-noetic-urdf
    - ros-noetic-xacro
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
