package:
  name: ros-noetic-jackal-control
  version: 0.8.5
about:
  home: http://wiki.ros.org/jackal_control
  license:
    - BSD
  summary: Controllers for Jackal
  maintainers:
    - Mike Purvis (mpurvis@clearpathrobotics.com)
extra:
  recipe-maintainers:
    - robostack
build:
  number: 3
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh



source:
  git_url: https://github.com/clearpath-gbp/jackal-release.git
  git_rev: release/noetic/jackal_control/0.8.5-1
  folder: ros-noetic-jackal-control/src/work
requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-roslaunch
    - ros-noetic-controller-manager
    - ros-noetic-interactive-marker-twist-server
    - ros-noetic-diff-drive-controller
    - ros-noetic-joint-state-controller
    - ros-noetic-joy
    - ros-noetic-robot-localization
    - ros-noetic-teleop-twist-joy
    - ros-noetic-topic-tools
    - ros-noetic-twist-mux
  run:
    - python
    - ros-noetic-controller-manager
    - ros-noetic-interactive-marker-twist-server
    - ros-noetic-diff-drive-controller
    - ros-noetic-joint-state-controller
    - ros-noetic-joy
    - ros-noetic-robot-localization
    - ros-noetic-teleop-twist-joy
    - ros-noetic-topic-tools
    - ros-noetic-twist-mux
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
