package:
  name: ros-noetic-jackal-base
  version: 0.6.1
about:
  home: http://wiki.ros.org/Robots/Jackal
  license:
    - BSD
  summary: Jackal's mobility and sensor base.
  maintainers:
    - Mike Purvis (mpurvis@clearpathrobotics.com)
extra:
  recipe-maintainers:
    - robostack
build:
  number: 0
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
source:
  git_url: https://github.com/clearpath-gbp/jackal_robot-release.git
  git_rev: release/melodic/jackal_base/0.6.1-1
  folder: ros-noetic-jackal-base/src/work
requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-controller-manager
    - ros-noetic-diagnostic-updater
    - ros-noetic-geometry-msgs
    - ros-noetic-hardware-interface
    - ros-noetic-nmea-msgs
    - ros-noetic-realtime-tools
    - ros-noetic-roscpp
    - ros-noetic-roslaunch
    - ros-noetic-roslint
    - ros-noetic-rosserial-server
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-teleop-twist-joy
    - ros-noetic-topic-tools
    - ros-noetic-controller-manager
    - ros-noetic-diagnostic-aggregator
    - ros-noetic-diagnostic-updater
    - ros-noetic-diff-drive-controller
    - ros-noetic-geometry-msgs
    - ros-noetic-imu-filter-madgwick
    - ros-noetic-nmea-msgs
    - ros-noetic-nmea-navsat-driver
    - ros-noetic-realtime-tools
    - ros-noetic-rosserial-python
    - ros-noetic-rosserial-server
    - ros-noetic-sensor-msgs
    - ros-noetic-teleop-twist-joy
    - ros-noetic-tf
    - ros-noetic-topic-tools
  run:
    - python
    - ros-noetic-controller-manager
    - ros-noetic-diagnostic-aggregator
    - ros-noetic-diagnostic-updater
    - ros-noetic-diff-drive-controller
    - ros-noetic-geometry-msgs
    - ros-noetic-imu-filter-madgwick
    - ros-noetic-nmea-msgs
    - ros-noetic-nmea-navsat-driver
    - ros-noetic-realtime-tools
    - ros-noetic-rosserial-python
    - ros-noetic-rosserial-server
    - ros-noetic-sensor-msgs
    - ros-noetic-teleop-twist-joy
    - ros-noetic-tf
    - ros-noetic-topic-tools
    - ros-noetic-controller-manager
    - ros-noetic-diagnostic-aggregator
    - ros-noetic-diagnostic-updater
    - ros-noetic-diff-drive-controller
    - ros-noetic-geometry-msgs
    - ros-noetic-imu-filter-madgwick
    - ros-noetic-nmea-msgs
    - ros-noetic-nmea-navsat-driver
    - ros-noetic-realtime-tools
    - ros-noetic-rosserial-python
    - ros-noetic-rosserial-server
    - ros-noetic-sensor-msgs
    - ros-noetic-teleop-twist-joy
    - ros-noetic-tf
    - ros-noetic-topic-tools