package:
  name: ros-noetic-jackal-base
  version: 0.7.11
about:
  homepage: http://wiki.ros.org/Robots/Jackal
  license: BSD-3-Clause
  summary: Jackal's mobility and sensor base.

extra:
  recipe-maintainers:
    - robostack
build:
  number: 4
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix else '%RECIPE_DIR%\\bld_catkin.bat' }}


source:
  git: https://github.com/clearpath-gbp/jackal_robot-release.git
  tag: release/noetic/jackal_base/0.7.11-1
  target_directory: ros-noetic-jackal-base/src/work
requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-controller-manager
    - ros-noetic-diagnostic-updater
    - ros-noetic-geometry-msgs
    - ros-noetic-hardware-interface
    - ros-noetic-nmea-msgs
    - ros-noetic-realtime-tools
    - ros-noetic-roscpp
    - ros-noetic-roslaunch
    - ros-noetic-roslint
    - ros-noetic-rosserial-server
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-teleop-twist-joy
    - ros-noetic-topic-tools
    - ros-noetic-diagnostic-aggregator
    - ros-noetic-diff-drive-controller
    - ros-noetic-imu-filter-madgwick
    - ros-noetic-nmea-navsat-driver
    - ros-noetic-rosserial-python
    - ros-noetic-tf
    - ros-noetic-jackal-msgs
  run:
    - python
    - ros-noetic-controller-manager
    - ros-noetic-diagnostic-aggregator
    - ros-noetic-diagnostic-updater
    - ros-noetic-diff-drive-controller
    - ros-noetic-geometry-msgs
    - ros-noetic-imu-filter-madgwick
    - ros-noetic-nmea-msgs
    - ros-noetic-nmea-navsat-driver
    - ros-noetic-realtime-tools
    - ros-noetic-rosserial-python
    - ros-noetic-rosserial-server
    - ros-noetic-sensor-msgs
    - ros-noetic-teleop-twist-joy
    - ros-noetic-tf
    - ros-noetic-topic-tools
    - ros-noetic-jackal-msgs
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}