package:
  name: ros-noetic-dynamic-reconfigure
  version: 1.7.3
source:
  git_url: https://github.com/ros-gbp/dynamic_reconfigure-release.git
  git_rev: release/noetic/dynamic_reconfigure/1.7.3-1
  folder: ros-noetic-dynamic-reconfigure/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - boost-cpp
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-cpp-common
    - ros-noetic-message-generation
    - ros-noetic-roscpp
    - ros-noetic-roscpp-serialization
    - ros-noetic-rostest
    - ros-noetic-std-msgs
  run:
    - boost-cpp
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-message-runtime
    - ros-noetic-roscpp
    - ros-noetic-roslib
    - ros-noetic-rospy
    - ros-noetic-rosservice
    - ros-noetic-std-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
