package:
  name: ros-noetic-rqt-robot-plugins
  version: 0.5.8
source:
  git_url: https://github.com/ros-gbp/rqt_robot_plugins-release.git
  git_rev: release/noetic/rqt_robot_plugins/0.5.8-1
  folder: ros-noetic-rqt-robot-plugins/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-rqt-moveit
    - ros-noetic-rqt-nav-view
    - ros-noetic-rqt-pose-view
    - ros-noetic-rqt-robot-dashboard
    - ros-noetic-rqt-robot-monitor
    - ros-noetic-rqt-robot-steering
    - ros-noetic-rqt-runtime-monitor
    - ros-noetic-rqt-rviz
    - ros-noetic-rqt-tf-tree
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-rqt-moveit
    - ros-noetic-rqt-nav-view
    - ros-noetic-rqt-pose-view
    - ros-noetic-rqt-robot-dashboard
    - ros-noetic-rqt-robot-monitor
    - ros-noetic-rqt-robot-steering
    - ros-noetic-rqt-runtime-monitor
    - ros-noetic-rqt-rviz
    - ros-noetic-rqt-tf-tree
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
