# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-noetic-image-view2
  version: 2.2.15
source:
  git: https://github.com/tork-a/jsk_common-release.git
  tag: release/noetic/image_view2/2.2.15-4
  target_directory: ros-noetic-image-view2/src/work

build:
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix else '%RECIPE_DIR%\\bld_catkin.bat' }}
  number: 18
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-distro-mutex 0.6.* noetic_*
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
    - ros-noetic-geometry-msgs
    - ros-noetic-image-geometry
    - ros-noetic-image-transport
    - ros-noetic-image-view
    - ros-noetic-message-filters
    - ros-noetic-message-generation
    - ros-noetic-pcl-ros
    - ros-noetic-roscpp
    - ros-noetic-rostest
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-tf
    - scipy
    - if: linux
      then:
        - libgl-devel
        - libopengl-devel
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
  run:
    - python
    - ros-distro-mutex 0.6.* noetic_*
    - ros-noetic-cv-bridge
    - ros-noetic-geometry-msgs
    - ros-noetic-image-geometry
    - ros-noetic-image-transport
    - ros-noetic-image-view
    - ros-noetic-message-filters
    - ros-noetic-message-runtime
    - ros-noetic-pcl-ros
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-tf
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
