package:
  name: ros-noetic-roswtf
  version: 1.15.15
source:
  git_url: https://github.com/ros-gbp/ros_comm-release.git
  git_rev: release/noetic/roswtf/1.15.15-1
  folder: ros-noetic-roswtf/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-cmake-modules
    - ros-noetic-rosbag
    - ros-noetic-roslang
    - ros-noetic-rostest
    - ros-noetic-std-srvs
  run:
    - paramiko
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-rosbuild
    - ros-noetic-rosgraph
    - ros-noetic-roslaunch
    - ros-noetic-roslib
    - ros-noetic-rosnode
    - ros-noetic-rosservice
    - rospkg
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
