package:
  name: ros-noetic-jackal-msgs
  version: 0.8.10
about:
  homepage: http://wiki.ros.org/jackal_msgs
  license: BSD-3-Clause
  summary: Messages exclusive to Jackal, especially for representing low-level motor commands and sensors.

extra:
  recipe-maintainers:
    - robostack
build:
  number: 4
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix else '%RECIPE_DIR%\\bld_catkin.bat' }}


source:
  git: https://github.com/clearpath-gbp/jackal-release.git
  tag: release/noetic/jackal_msgs/0.8.10-1
  target_directory: ros-noetic-jackal-msgs/src/work
requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-message-generation
    - ros-noetic-std-msgs
    - ros-noetic-message-runtime
  run:
    - python
    - ros-noetic-message-runtime
    - ros-noetic-std-msgs
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}