package:
  name: ros-noetic-jackal-navigation
  version: 0.8.10
about:
  homepage: http://wiki.ros.org/jackal_navigation
  license: BSD-3-Clause
  summary: Launch files and code for autonomous navigation of the Jackal

extra:
  recipe-maintainers:
    - robostack
build:
  number: 21
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix else '%RECIPE_DIR%\\bld_catkin.bat' }}


source:
  git: https://github.com/clearpath-gbp/jackal-release.git
  tag: release/noetic/jackal_navigation/0.8.10-1
  target_directory: ros-noetic-jackal-navigation/src/work
requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-roslaunch
    - ros-noetic-amcl
    - ros-noetic-gmapping
    - ros-noetic-map-server
    - ros-noetic-move-base
    - ros-noetic-urdf
    - ros-noetic-xacro
  run:
    - python
    - ros-noetic-amcl
    - ros-noetic-gmapping
    - ros-noetic-map-server
    - ros-noetic-move-base
    - ros-noetic-urdf
    - ros-noetic-xacro
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}