package:
  name: ros-noetic-jackal-desktop
  version: 0.4.0
about:
  home: http://wiki.ros.org/jackal_desktop
  license:
    - BSD
  summary: Packages for working with Jackal from a ROS desktop.
  maintainers:
    - Mike Purvis (mpurvis@clearpathrobotics.com)
extra:
  recipe-maintainers:
    - robostack
build:
  number: 0
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
source:
  git_url: https://github.com/clearpath-gbp/jackal_desktop-release.git
  git_rev: release/melodic/jackal_desktop/0.6.1-1
  folder: ros-noetic-jackal-desktop/src/work
requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-jackal-viz
  run:
    - python
    - ros-noetic-jackal-viz
    - ros-noetic-jackal-viz
