package:
  name: ros-noetic-rqt-image-view
  version: 0.4.16
source:
  git_url: https://github.com/ros-gbp/rqt_image_view-release.git
  git_rev: release/noetic/rqt_image_view/0.4.16-1
  folder: ros-noetic-rqt-image-view/src/work
  patches:
    - patch/ros-noetic-rqt-image-view.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - qt-main
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
    - ros-noetic-geometry-msgs
    - ros-noetic-image-transport
    - ros-noetic-rqt-gui
    - ros-noetic-rqt-gui-cpp
    - ros-noetic-sensor-msgs
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-cv-bridge
    - ros-noetic-geometry-msgs
    - ros-noetic-image-transport
    - ros-noetic-rqt-gui
    - ros-noetic-rqt-gui-cpp
    - ros-noetic-sensor-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
