package:
  name: ros-noetic-ros-core
  version: 1.5.0
source:
  git_url: https://github.com/ros-gbp/metapackages-release.git
  git_rev: release/noetic/ros_core/1.5.0-1
  folder: ros-noetic-ros-core/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-class-loader
    - ros-noetic-cmake-modules
    - ros-noetic-common-msgs
    - ros-noetic-gencpp
    - ros-noetic-geneus
    - ros-noetic-genlisp
    - ros-noetic-genmsg
    - ros-noetic-gennodejs
    - ros-noetic-genpy
    - ros-noetic-message-generation
    - ros-noetic-message-runtime
    - ros-noetic-pluginlib
    - ros-noetic-ros
    - ros-noetic-ros-comm
    - ros-noetic-rosbag-migration-rule
    - ros-noetic-rosconsole
    - ros-noetic-rosconsole-bridge
    - ros-noetic-roscpp-core
    - ros-noetic-rosgraph-msgs
    - ros-noetic-roslisp
    - ros-noetic-rospack
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
