package:
  name: ros-noetic-ros-comm
  version: 1.15.15
source:
  git_url: https://github.com/ros-gbp/ros_comm-release.git
  git_rev: release/noetic/ros_comm/1.15.15-1
  folder: ros-noetic-ros-comm/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-message-filters
    - ros-noetic-ros
    - ros-noetic-rosbag
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-rosgraph
    - ros-noetic-rosgraph-msgs
    - ros-noetic-roslaunch
    - ros-noetic-roslisp
    - ros-noetic-rosmaster
    - ros-noetic-rosmsg
    - ros-noetic-rosnode
    - ros-noetic-rosout
    - ros-noetic-rosparam
    - ros-noetic-rospy
    - ros-noetic-rosservice
    - ros-noetic-rostest
    - ros-noetic-rostopic
    - ros-noetic-roswtf
    - ros-noetic-std-srvs
    - ros-noetic-topic-tools
    - ros-noetic-xmlrpcpp
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-message-filters
    - ros-noetic-ros
    - ros-noetic-rosbag
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-rosgraph
    - ros-noetic-rosgraph-msgs
    - ros-noetic-roslaunch
    - ros-noetic-roslisp
    - ros-noetic-rosmaster
    - ros-noetic-rosmsg
    - ros-noetic-rosnode
    - ros-noetic-rosout
    - ros-noetic-rosparam
    - ros-noetic-rospy
    - ros-noetic-rosservice
    - ros-noetic-rostest
    - ros-noetic-rostopic
    - ros-noetic-roswtf
    - ros-noetic-std-srvs
    - ros-noetic-topic-tools
    - ros-noetic-xmlrpcpp
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
