package:
  name: ros-noetic-tf
  version: 1.13.2
source:
  git_url: https://github.com/ros-gbp/geometry-release.git
  git_rev: release/noetic/tf/1.13.2-1
  folder: ros-noetic-tf/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - graphviz
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-angles
    - ros-noetic-catkin
    - ros-noetic-geometry-msgs
    - ros-noetic-message-filters
    - ros-noetic-message-generation
    - ros-noetic-message-runtime
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-rostest
    - ros-noetic-rostime
    - ros-noetic-rosunit
    - ros-noetic-roswtf
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf2-ros
  run:
    - graphviz
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-geometry-msgs
    - ros-noetic-message-filters
    - ros-noetic-message-runtime
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-roswtf
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf2-ros
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
