package:
  name: ros-noetic-stereo-image-proc
  version: 1.17.0
source:
  git_url: https://github.com/ros-gbp/image_pipeline-release.git
  git_rev: release/noetic/stereo_image_proc/1.17.0-1
  folder: ros-noetic-stereo-image-proc/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-image-geometry
    - ros-noetic-image-proc
    - ros-noetic-image-transport
    - ros-noetic-message-filters
    - ros-noetic-nodelet
    - ros-noetic-rostest
    - ros-noetic-sensor-msgs
    - ros-noetic-stereo-msgs
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-cv-bridge
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-image-geometry
    - ros-noetic-image-proc
    - ros-noetic-image-transport
    - ros-noetic-message-filters
    - ros-noetic-nodelet
    - ros-noetic-sensor-msgs
    - ros-noetic-stereo-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
