:: Generated by vinca http://github.com/RoboStack/vinca.
:: DO NOT EDIT!
@if not defined CONDA_PREFIX goto:eof

@set ROS_OS_OVERRIDE=
@set ROS_DISTRO=
@set ROS_ETC_DIR=
@set ROS_PACKAGE_PATH=
@set ROS_PYTHON_VERSION=
@set ROS_VERSION=
@set PYTHONHOME=
@set PYTHONPATH=
@set CMAKE_PREFIX_PATH=
@set AMENT_PREFIX_PATH=
@set COLCON_PREFIX_PATH=
@set QT_PLUGIN_PATH=
@set ROS_LOCALHOST_ONLY=
@set ament_python_executable=
