package:
  name: ros-noetic-jackal-simulator
  version: 0.4.0
about:
  homepage: http://wiki.ros.org/jackal_simulator
  license: BSD-3-Clause
  summary: Packages for simulating Jackal.

extra:
  recipe-maintainers:
    - robostack
build:
  number: 21
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix else '%RECIPE_DIR%\\..\\..\\bld_catkin.bat' }}

source:
  git: https://github.com/clearpath-gbp/jackal_simulator-release.git
  tag: release/noetic/jackal_simulator/0.4.0-1
  target_directory: ros-noetic-jackal-simulator/src/work
requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-jackal-gazebo
  run:
    - python
    - ros-noetic-jackal-gazebo
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}