# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-noetic-rtabmap
  version: 0.21.9
source:
  git: https://github.com/introlab/rtabmap-release.git
  tag: release/noetic/rtabmap/0.21.9-1
  target_directory: ros-noetic-rtabmap/src/work
  patches:
    - patch/ros-noetic-rtabmap.patch

build:
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix else '%RECIPE_DIR%\\bld_catkin.bat' }}
  number: 18
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: build_platform != target_platform
      then:
        - pybind11
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - libboost-devel
    - liblzma-devel
    - numpy
    - pcl
    - pip
    - proj
    - pybind11
    - python
    - ros-distro-mutex 0.6.* noetic_*
    - ros-noetic-cv-bridge
    - ros-noetic-grid-map-core
    - ros-noetic-gtsam
    - ros-noetic-libg2o
    - ros-noetic-qt-gui-cpp
    - sqlite 3.*
    - tbb-devel
    - vtk-base
    - zlib
    - if: linux
      then:
        - libgl-devel
        - libopengl-devel
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
  run:
    - libboost-devel
    - pcl
    - python
    - ros-distro-mutex 0.6.* noetic_*
    - ros-noetic-cv-bridge
    - ros-noetic-grid-map-core
    - ros-noetic-gtsam
    - ros-noetic-libg2o
    - ros-noetic-qt-gui-cpp
    - sqlite
    - vtk-base
    - zlib
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
