package:
  name: ros-noetic-jackal-robot
  version: 0.6.1
about:
  home: http://wiki.ros.org/Robots/Jackal
  license:
    - BSD
  summary: Metapackage of software to install on Jackal.
  maintainers:
    - Mike Purvis (mpurvis@clearpathrobotics.com)
extra:
  recipe-maintainers:
    - robostack
build:
  number: 0
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
source:
  git_url: https://github.com/clearpath-gbp/jackal_robot-release.git
  git_rev: release/melodic/jackal_robot/0.6.1-1
  folder: ros-noetic-jackal-robot/src/work
requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-jackal-bringup
  run:
    - python
    - ros-noetic-jackal-bringup
    - ros-noetic-jackal-bringup
