package:
  name: ros-noetic-rqt-logger-level
  version: 0.4.11
source:
  git_url: https://github.com/ros-gbp/rqt_logger_level-release.git
  git_rev: release/noetic/rqt_logger_level/0.4.11-1
  folder: ros-noetic-rqt-logger-level/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-python-qt-binding
    - ros-noetic-rosnode
    - ros-noetic-rospy
    - ros-noetic-rosservice
    - ros-noetic-rqt-gui
    - ros-noetic-rqt-gui-py
    - rospkg
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
