package:
  name: ros-noetic-pinocchio
  version: "3.3.1"

build:
  number: 0

requirements:
  run:
    - pinocchio ==3.3.1

about:
  homepage: https://github.com/conda-forge/pinocchio-feedstock
  license: BSD-2-Clause
  summary: |
    A fast and flexible implementation of Rigid Body Dynamics algorithms and their analytical derivatives
extra:
  recipe-maintainers:
    - ros-forge
