package:
  name: ros-noetic-desktop
  version: 1.5.0
source:
  git_url: https://github.com/ros-gbp/metapackages-release.git
  git_rev: release/noetic/desktop/1.5.0-1
  folder: ros-noetic-desktop/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-angles
    - ros-noetic-common-tutorials
    - ros-noetic-geometry-tutorials
    - ros-noetic-joint-state-publisher-gui
    - ros-noetic-robot
    - ros-noetic-ros-tutorials
    - ros-noetic-roslint
    - ros-noetic-urdf-tutorial
    - ros-noetic-visualization-tutorials
    - ros-noetic-viz
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
