package:
  name: ros-noetic-jackal-control
  version: 0.8.10
about:
  homepage: http://wiki.ros.org/jackal_control
  license: BSD-3-Clause
  summary: Controllers for Jackal

extra:
  recipe-maintainers:
    - robostack
build:
  number: 4
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix else '%RECIPE_DIR%\\bld_catkin.bat' }}



source:
  git: https://github.com/clearpath-gbp/jackal-release.git
  tag: release/noetic/jackal_control/0.8.10-1
  target_directory: ros-noetic-jackal-control/src/work
requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-roslaunch
    - ros-noetic-controller-manager
    - ros-noetic-interactive-marker-twist-server
    - ros-noetic-diff-drive-controller
    - ros-noetic-joint-state-controller
    - ros-noetic-joy
    - ros-noetic-robot-localization
    - ros-noetic-teleop-twist-joy
    - ros-noetic-topic-tools
    - ros-noetic-twist-mux
  run:
    - python
    - ros-noetic-controller-manager
    - ros-noetic-interactive-marker-twist-server
    - ros-noetic-diff-drive-controller
    - ros-noetic-joint-state-controller
    - ros-noetic-joy
    - ros-noetic-robot-localization
    - ros-noetic-teleop-twist-joy
    - ros-noetic-topic-tools
    - ros-noetic-twist-mux
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}