package:
  name: ros-distro-mutex
  version: 0.6.0

build:
  number: 0
  # Note: keep in sync with build number
  # Cannot be done automatically, see https://github.com/mamba-org/boa/issues/278
  string: noetic_0

requirements:
  # NOTE:
  # The idea with automatically adding versions to run_exports doesn't
  # work since we don't want all these dependencies as run deps of all ROS
  # packages. Therefore I am currently manually adding them to run_constrained.
  # This has to be synchronized with our current conda_build_config all the time :(
  # host:
  #   # values here should 
  #   - log4cxx
  #   - poco
  #   - pcl
  #   - opencv
  #   - gazebo
  #   - ogre
  #   - qt
  # run:
  # values here should be applied from run_exports!
  # if the upstream package does not have run_exports
  # please change it in the conda_build_config.yaml!
  # libabseil and libprotobuf added here as a workaround for
  # https://github.com/RoboStack/ros-noetic/issues/459
  run_constraints:
    - libboost 1.86.*
    - libboost-devel 1.86.*
    - pcl 1.14.1.*
    - gazebo 11.*
    - libprotobuf 5.28.3.*
    - ogre 1.10.12.*
    - libpqxx 7.8.*
    - sip 6.7.*
    - harfbuzz 10.*

  run_exports:
    weak:
      - ${{ pin_subpackage('ros-distro-mutex', upper_bound='x.x') }}

about:
  homepage: https://github.com/robostack/ros-noetic
  license: BSD-3-Clause
  summary: |
    The ROS distro mutex. To switch between ROS versions, you need to change the mutex.
    E.g. mamba install ros-distro-mutex=*=noetic to switch to noetic.

extra:
  recipe-maintainers:
    - ros-forge
