package:
  name: ros-noetic-jackal-msgs
  version: 0.8.5
about:
  home: http://wiki.ros.org/jackal_msgs
  license:
    - BSD
  summary: Messages exclusive to Jackal, especially for representing low-level motor commands and sensors.
  maintainers:
    - Mike Purvis (mpurvis@clearpathrobotics.com)
extra:
  recipe-maintainers:
    - robostack
build:
  number: 3
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh


source:
  git_url: https://github.com/clearpath-gbp/jackal-release.git
  git_rev: release/noetic/jackal_msgs/0.8.5-1
  folder: ros-noetic-jackal-msgs/src/work
requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-message-generation
    - ros-noetic-std-msgs
    - ros-noetic-message-runtime
  run:
    - python
    - ros-noetic-message-runtime
    - ros-noetic-std-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
