jobs:
  stage_0_job_0:
    name: ros-ign-bridge ros-ign-gazebo ros-ign-image ros-ign-gazebo-demos
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-noetic-ros-ign-bridge ros-noetic-ros-ign-gazebo ros-noetic-ros-ign-image
        ros-noetic-ros-ign-gazebo-demos
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-noetic-ros-ign-bridge ros-noetic-ros-ign-gazebo ros-noetic-ros-ign-image
          ros-noetic-ros-ign-gazebo-demos
        DOCKER_IMAGE: condaforge/linux-anvil-cos7-x86_64
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
  stage_1_job_1:
    name: ros-ign
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-noetic-ros-ign
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-noetic-ros-ign
        DOCKER_IMAGE: condaforge/linux-anvil-cos7-x86_64
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
name: build_linux
on:
  push:
    branches:
    - buildbranch_linux
