package:
  name: ros-noetic-nodelet
  version: 1.10.2
source:
  git_url: https://github.com/ros-gbp/nodelet_core-release.git
  git_rev: release/noetic/nodelet/1.10.2-1
  folder: ros-noetic-nodelet/src/work
  patches:
    - patch/ros-noetic-nodelet.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - boost
    - libuuid
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-bondcpp
    - ros-noetic-catkin
    - ros-noetic-cmake-modules
    - ros-noetic-message-generation
    - ros-noetic-pluginlib
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-std-msgs
  run:
    - boost
    - libuuid
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-bondcpp
    - ros-noetic-message-runtime
    - ros-noetic-pluginlib
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-rospy
    - ros-noetic-std-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
