package:
  name: ros-noetic-rosbridge-library
  version: 0.11.16
source:
  git_url: https://github.com/RobotWebTools-release/rosbridge_suite-release.git
  git_rev: release/noetic/rosbridge_library/0.11.16-2
  folder: ros-noetic-rosbridge-library/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pillow
    - pip
    - sel(build_platform == target_platform): pkg-config
    - pymongo
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-actionlib-msgs
    - ros-noetic-catkin
    - ros-noetic-diagnostic-msgs
    - ros-noetic-geometry-msgs
    - ros-noetic-message-generation
    - ros-noetic-nav-msgs
    - ros-noetic-rospy-tutorials
    - ros-noetic-rostest
    - ros-noetic-rosunit
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-stereo-msgs
    - ros-noetic-tf2-msgs
    - ros-noetic-trajectory-msgs
    - ros-noetic-visualization-msgs
    - setuptools
  run:
    - pillow
    - pymongo
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-geometry-msgs
    - ros-noetic-message-runtime
    - ros-noetic-roscpp
    - ros-noetic-rosgraph
    - ros-noetic-rospy
    - ros-noetic-rosservice
    - ros-noetic-rostopic
    - ros-noetic-std-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
